# Curated trivia tuples: (question, [opt0..3], correct_index)
# Used by gen_expansion.py — 700 rows + 100 from capital generators = 800.

TE_EASY: list[tuple[str, list[str], int]] = [
    ("Who painted the Mona Lisa?", ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], 1),
    ("Which planet is known as the Morning Star?", ["Mars", "Venus", "Mercury", "Jupiter"], 1),
    ("What is the largest mammal on Earth?", ["African elephant", "Blue whale", "Giraffe", "Orca"], 1),
    ("In chess, which piece moves only diagonally?", ["Rook", "Knight", "Bishop", "Pawn"], 2),
    ("Who wrote 'Romeo and Juliet'?", ["Dickens", "Shakespeare", "Austen", "Twain"], 1),
    ("What is the smallest prime number?", ["0", "1", "2", "3"], 2),
    ("Which sport uses a shuttlecock?", ["Squash", "Badminton", "Tennis", "Volleyball"], 1),
    ("What is the main ingredient in hummus?", ["Lentils", "Chickpeas", "Black beans", "Rice"], 1),
    ("Who wrote 'Pride and Prejudice'?", ["Brontë", "Jane Austen", "Woolf", "Shelley"], 1),
    ("Which composer wrote 'The Four Seasons'?", ["Mozart", "Vivaldi", "Bach", "Handel"], 1),
    ("What is the boiling point of water in Celsius?", ["90°C", "100°C", "212°C", "0°C"], 1),
    ("How many sides does an octagon have?", ["6", "7", "8", "10"], 2),
    ("What is the largest ocean?", ["Atlantic", "Indian", "Arctic", "Pacific"], 3),
    ("Which animal is known as the 'Ship of the Desert'?", ["Horse", "Camel", "Elephant", "Llama"], 1),
    ("What is the capital of England?", ["Manchester", "London", "Liverpool", "Oxford"], 1),
    ("Which gas do plants absorb for photosynthesis?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], 2),
    ("What is the hardest natural substance on Earth?", ["Steel", "Diamond", "Granite", "Iron"], 1),
    ("Who directed 'E.T. the Extra-Terrestrial'?", ["Lucas", "Spielberg", "Coppola", "Scorsese"], 1),
    ("What is 12 × 12?", ["124", "132", "144", "156"], 2),
    ("Which month has 28 or 29 days?", ["January", "February", "March", "April"], 1),
    ("What is the largest planet in our solar system?", ["Saturn", "Jupiter", "Neptune", "Earth"], 1),
    ("What do bees produce?", ["Silk", "Honey", "Maple syrup", "Wax candles"], 1),
    ("Which instrument has 88 keys?", ["Violin", "Piano", "Harp", "Organ"], 1),
    ("What is the main language of Mexico?", ["English", "Spanish", "Portuguese", "French"], 1),
    ("How many continents are there (commonly taught)?", ["5", "6", "7", "8"], 2),
    ("What is the color of a ruby?", ["Blue", "Red", "Green", "Yellow"], 1),
    ("Which bird is the largest living bird?", ["Eagle", "Ostrich", "Penguin", "Albatross"], 1),
    ("What is the center of our solar system?", ["Earth", "Moon", "Sun", "Jupiter"], 2),
    ("Who wrote 'The Hobbit'?", ["Lewis", "Tolkien", "Rowling", "Sanderson"], 1),
    ("What is frozen water called?", ["Steam", "Ice", "Vapor", "Mist"], 1),
    ("Which sense organ detects sound?", ["Eyes", "Ears", "Nose", "Tongue"], 1),
    ("What is the largest land animal?", ["Hippo", "African elephant", "Giraffe", "Rhino"], 1),
    ("What shape has three sides?", ["Square", "Triangle", "Pentagon", "Circle"], 1),
    ("Which metal is liquid at room temperature (common)?", ["Iron", "Mercury", "Gold", "Silver"], 1),
    ("What is the chemical symbol for gold?", ["Go", "Au", "Ag", "Gd"], 1),
    ("Who painted 'Starry Night'?", ["Picasso", "Van Gogh", "Monet", "Dalí"], 1),
    ("What is the fastest land animal?", ["Lion", "Cheetah", "Horse", "Leopard"], 1),
    ("Which ocean lies between Africa and Australia?", ["Atlantic", "Indian", "Pacific", "Arctic"], 1),
    ("What is a group of lions called?", ["Pack", "Pride", "Herd", "Flock"], 1),
    ("What is H2O commonly called?", ["Salt", "Water", "Sugar", "Oxygen"], 1),
    ("Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Saturn"], 1),
    ("What is the main gas in Earth's atmosphere?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], 2),
    ("How many hours in a day?", ["12", "24", "36", "48"], 1),
    ("What color do you get mixing blue and yellow?", ["Red", "Green", "Purple", "Orange"], 1),
    ("Which is bigger: a kilometer or a meter?", ["Meter", "Kilometer", "Equal", "Depends"], 1),
    ("What is the tallest mountain in the world (above sea level)?", ["K2", "Kilimanjaro", "Mount Everest", "Denali"], 2),
    ("Who wrote '1984'?", ["Huxley", "Orwell", "Bradbury", "Atwood"], 1),
    ("What is the largest island country?", ["Philippines", "Japan", "Indonesia", "Madagascar"], 2),
    ("Which tool measures temperature?", ["Ruler", "Thermometer", "Scale", "Barometer"], 1),
    ("What is the opposite of hot?", ["Warm", "Cold", "Wet", "Loud"], 1),
    ("How many players on a soccer team on the field?", ["9", "10", "11", "12"], 2),
    ("What is the capital of Spain?", ["Barcelona", "Madrid", "Seville", "Valencia"], 1),
    ("Which element has chemical symbol O?", ["Gold", "Oxygen", "Osmium", "Olivine"], 1),
    ("What is a baby dog called?", ["Kitten", "Puppy", "Calf", "Chick"], 1),
    ("Which season comes after winter?", ["Summer", "Spring", "Fall", "Autumn"], 1),
    ("What is the largest bird that can fly?", ["Albatross", "Condor", "Ostrich", "Penguin"], 0),
    ("What is paper primarily made from?", ["Plastic", "Wood fiber", "Metal", "Glass"], 1),
    ("Which direction does the sun rise?", ["North", "East", "West", "South"], 1),
    ("What is the largest fish (not a mammal)?", ["Blue whale", "Whale shark", "Dolphin", "Orca"], 1),
    ("What is the study of living things called?", ["Geology", "Biology", "Physics", "Chemistry"], 1),
]

TE_MED: list[tuple[str, list[str], int]] = [
    ("Which Greek hero slew the Minotaur?", ["Perseus", "Theseus", "Hercules", "Odysseus"], 1),
    ("What is the longest bone in the human body?", ["Tibia", "Femur", "Humerus", "Radius"], 1),
    ("Which blood type is the universal recipient?", ["O-", "AB+", "A+", "B-"], 1),
    ("What does 'HTTP' stand for?", ["HyperText Transfer Protocol", "High Text Protocol", "Host Transfer Protocol", "Hyperlink Text Protocol"], 0),
    ("Which country is credited with inventing paper?", ["India", "China", "Egypt", "Greece"], 1),
    ("Who wrote 'Crime and Punishment'?", ["Tolstoy", "Dostoevsky", "Chekhov", "Gogol"], 1),
    ("What is the capital of Canada?", ["Toronto", "Montreal", "Ottawa", "Vancouver"], 2),
    ("Which element has atomic number 47?", ["Gold", "Silver", "Copper", "Zinc"], 1),
    ("What is the largest moon of Saturn?", ["Europa", "Titan", "Ganymede", "Io"], 1),
    ("Who composed 'The Magic Flute'?", ["Beethoven", "Mozart", "Haydn", "Schubert"], 1),
    ("Which war ended with the Treaty of Versailles?", ["WWII", "WWI", "Crimean War", "Napoleonic Wars"], 1),
    ("What is the SI unit of frequency?", ["Joule", "Hertz", "Newton", "Pascal"], 1),
    ("What is the chemical formula for table salt?", ["NaCl", "KCl", "NaOH", "HCl"], 0),
    ("Who wrote 'Les Misérables'?", ["Dumas", "Hugo", "Flaubert", "Zola"], 1),
    ("What is the largest internal organ?", ["Heart", "Liver", "Brain", "Lung"], 1),
    ("Which planet rotates on its side?", ["Mars", "Uranus", "Neptune", "Venus"], 1),
    ("What is the study of weather called?", ["Geology", "Meteorology", "Astronomy", "Ecology"], 1),
    ("Who painted 'The Persistence of Memory'?", ["Picasso", "Dalí", "Miró", "Gris"], 1),
    ("What is the largest island in the world?", ["Borneo", "Greenland", "New Guinea", "Madagascar"], 1),
    ("Which ocean is between the Americas and Europe/Africa?", ["Indian", "Atlantic", "Pacific", "Arctic"], 1),
    ("What is the speed of sound in air (approx., m/s)?", ["150", "343", "500", "1,000"], 1),
    ("Who developed the theory of evolution by natural selection?", ["Mendel", "Darwin", "Newton", "Pasteur"], 1),
    ("What is the capital of Norway?", ["Bergen", "Oslo", "Trondheim", "Stavanger"], 1),
    ("Which metal is the best conductor of electricity?", ["Iron", "Copper", "Aluminum", "Lead"], 1),
    ("Who wrote 'War and Peace'?", ["Dostoevsky", "Tolstoy", "Pushkin", "Turgenev"], 1),
    ("What is the smallest planet in our solar system?", ["Mars", "Mercury", "Venus", "Pluto"], 1),
    ("Which vitamin is produced in skin with sunlight?", ["A", "B12", "C", "D"], 3),
    ("What is the largest species of shark?", ["Great white", "Whale shark", "Tiger shark", "Hammerhead"], 1),
    ("Who wrote 'Frankenstein'?", ["Poe", "Mary Shelley", "Stoker", "Wilde"], 1),
    ("What is the largest lake in Africa by area?", ["Tanganyika", "Victoria", "Malawi", "Chad"], 1),
    ("Which composer wrote the 'Moonlight Sonata'?", ["Mozart", "Beethoven", "Chopin", "Liszt"], 1),
    ("What is the capital of Egypt?", ["Alexandria", "Cairo", "Giza", "Luxor"], 1),
    ("Which gas is released by plants during photosynthesis?", ["CO₂", "Oxygen", "Nitrogen", "Methane"], 1),
    ("What is the square root of 256?", ["14", "15", "16", "17"], 2),
    ("Who wrote 'The Odyssey'?", ["Virgil", "Homer", "Sophocles", "Euripides"], 1),
    ("What is the largest bone in the arm?", ["Ulna", "Humerus", "Radius", "Carpal"], 1),
    ("Which is not a primary color of light (RGB)?", ["Red", "Green", "Yellow", "Blue"], 2),
    ("What is the main component of the Sun?", ["Iron", "Hydrogen", "Oxygen", "Carbon"], 1),
    ("Which country is home to kangaroos?", ["New Zealand", "Australia", "South Africa", "Brazil"], 1),
    ("What is the largest moon of Jupiter?", ["Io", "Ganymede", "Europa", "Callisto"], 1),
    ("Who wrote 'The Great Gatsby'?", ["Hemingway", "Fitzgerald", "Steinbeck", "Faulkner"], 1),
    ("What is the capital of Sweden?", ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], 1),
    ("Which element has symbol K?", ["Krypton", "Potassium", "Kryptonite", "Kelvin"], 1),
    ("What is the largest city in Canada by population?", ["Ottawa", "Toronto", "Montreal", "Vancouver"], 1),
    ("Which planet has the Great Red Spot?", ["Saturn", "Jupiter", "Neptune", "Uranus"], 1),
    ("Who composed 'Swan Lake'?", ["Mozart", "Tchaikovsky", "Stravinsky", "Rimsky-Korsakov"], 1),
    ("What is the largest desert (including cold deserts)?", ["Sahara", "Antarctic", "Gobi", "Arabian"], 1),
    ("Which river flows through Paris?", ["Rhine", "Seine", "Danube", "Thames"], 1),
    ("What is the hardest mineral on the Mohs scale?", ["Quartz", "Diamond", "Topaz", "Corundum"], 1),
    ("Who wrote 'Don Quixote'?", ["Cervantes", "Lope de Vega", "García Lorca", "Borges"], 0),
    ("What is the largest organ inside the human body (not skin)?", ["Brain", "Liver", "Lungs", "Heart"], 1),
    ("Which country invented the printing press (movable type, European)?", ["France", "Germany", "Italy", "England"], 1),
    ("What is the capital of Thailand?", ["Chiang Mai", "Bangkok", "Phuket", "Pattaya"], 1),
    ("Which gas makes up most of Earth's atmosphere?", ["Oxygen", "Nitrogen", "Argon", "CO₂"], 1),
    ("Who painted 'Guernica'?", ["Dalí", "Picasso", "Miró", "Goya"], 1),
    ("What is the largest volcano in the solar system?", ["Mauna Loa", "Olympus Mons", "Vesuvius", "Etna"], 1),
    ("Which sea separates Europe from Africa?", ["Black Sea", "Mediterranean", "Red Sea", "Caspian"], 1),
    ("What is the chemical symbol for iron?", ["Ir", "Fe", "F", "In"], 1),
    ("Who wrote 'One Hundred Years of Solitude'?", ["Borges", "Márquez", "Neruda", "Allende"], 1),
    ("What is the largest species of bear?", ["Black bear", "Grizzly", "Polar bear", "Panda"], 2),
]

TE_HARD: list[tuple[str, list[str], int]] = [
    ("What is the chemical symbol for tungsten?", ["Tu", "W", "Tg", "Tn"], 1),
    ("In what year did the Byzantine Empire fall?", ["1066", "1453", "1492", "1517"], 1),
    ("What is the half-life of Carbon-14 (years, approximate)?", ["~1,000", "~5,730", "~12,000", "~50,000"], 1),
    ("Who wrote 'Brothers Karamazov'?", ["Tolstoy", "Dostoevsky", "Turgenev", "Gogol"], 1),
    ("What is the most electronegative element?", ["Chlorine", "Oxygen", "Fluorine", "Nitrogen"], 2),
    ("Which amendment abolished slavery in the US?", ["12th", "13th", "14th", "15th"], 1),
    ("What is Euler's number e to two decimal places?", ["2.41", "2.72", "3.14", "1.62"], 1),
    ("What is the pH of pure water at 25°C?", ["6", "7", "8", "14"], 1),
    ("Who discovered penicillin?", ["Pasteur", "Fleming", "Lister", "Koch"], 1),
    ("What is the name of the boundary between Earth's crust and mantle?", ["Gutenberg", "Mohorovičić discontinuity", "Lehmann", "Conrad"], 1),
    ("Which particle was discovered at CERN in 2012?", ["Graviton", "Higgs boson", "Tachyon", "Gluon"], 1),
    ("What is the derivative of e^x?", ["x·e^(x-1)", "ln(x)", "e^x", "0"], 2),
    ("What law relates pressure and volume of a gas at constant temperature?", ["Charles's", "Boyle's", "Avogadro's", "Gay-Lussac's"], 1),
    ("What is the Krebs cycle primarily involved in?", ["DNA replication", "Cellular respiration", "Photosynthesis", "Translation"], 1),
    ("Which empire built Petra?", ["Roman", "Nabataean", "Persian", "Byzantine"], 1),
    ("What is the capital of Myanmar?", ["Yangon", "Naypyidaw", "Mandalay", "Bago"], 1),
    ("How many official languages does South Africa have?", ["5", "7", "11", "15"], 2),
    ("What is the tallest waterfall in the world?", ["Niagara", "Angel Falls", "Victoria", "Iguazu"], 1),
    ("Who composed 'The Rite of Spring'?", ["Debussy", "Stravinsky", "Ravel", "Prokofiev"], 1),
    ("What is Avogadro's number (order of magnitude)?", ["~10¹⁵", "~6×10²³", "~10³⁰", "~10⁸"], 1),
    ("Which country has the longest coastline?", ["Russia", "Canada", "Australia", "Indonesia"], 1),
    ("What is the term for a molecule with the same formula but different structure?", ["Isotope", "Isomer", "Allotrope", "Ion"], 1),
    ("In what year did the Berlin Wall fall?", ["1985", "1987", "1989", "1991"], 2),
    ("What is the SI unit of electric charge?", ["Volt", "Coulomb", "Ampere", "Ohm"], 1),
    ("Who wrote 'Ulysses'?", ["Woolf", "Joyce", "Beckett", "Yeats"], 1),
    ("What is the approximate age of Earth?", ["~2.5 billion years", "~4.5 billion years", "~6.5 billion years", "~10 billion years"], 1),
    ("Which blood type is the universal donor?", ["AB+", "A-", "O-", "B+"], 2),
    ("What is the chemical formula for sulfuric acid?", ["H2SO4", "H2SO3", "HSO4", "H2S"], 0),
    ("Who painted 'The Birth of Venus'?", ["Raphael", "Botticelli", "Titian", "Caravaggio"], 1),
    ("What is the largest moon of Neptune?", ["Proteus", "Triton", "Nereid", "Larissa"], 1),
    ("Which philosopher wrote 'Thus Spoke Zarathustra'?", ["Kant", "Nietzsche", "Hegel", "Schopenhauer"], 1),
    ("What is the speed of light in vacuum (m/s, exact defined value)?", ["299,792,458", "300,000,000", "3.14×10⁸", "150,000,000"], 0),
    ("What year was the Magna Carta signed?", ["1066", "1215", "1415", "1776"], 1),
    ("What is the densest naturally occurring element?", ["Lead", "Osmium", "Uranium", "Gold"], 1),
    ("Who wrote 'Invisible Man' (1952 novel)?", ["Baldwin", "Ellison", "Wright", "Hughes"], 1),
    ("What is the name of the supercontinent ~250 million years ago?", ["Laurasia", "Pangaea", "Gondwana", "Rodinia"], 1),
    ("Which composer was deaf later in life?", ["Mozart", "Beethoven", "Haydn", "Schubert"], 1),
    ("What is Planck's constant approximately?", ["1.6×10⁻¹⁹ J", "6.626×10⁻³⁴ J·s", "9.1×10⁻³¹ kg", "3×10⁸ m/s"], 1),
    ("What is the longest bone in the human body?", ["Tibia", "Femur", "Humerus", "Fibula"], 1),
    ("Which country was formerly known as Persia?", ["Iraq", "Iran", "Turkey", "Syria"], 1),
    ("What is the value of the golden ratio φ (approx.)?", ["1.41", "1.62", "2.72", "3.14"], 1),
    ("Who wrote 'The Stranger' (L'Étranger)?", ["Sartre", "Camus", "Beauvoir", "Proust"], 1),
    ("What is the largest desert in Australia?", ["Sahara", "Great Victoria Desert", "Gobi", "Kalahari"], 1),
    ("Which element has atomic number 79?", ["Silver", "Gold", "Mercury", "Platinum"], 1),
    ("What is the capital of Kazakhstan?", ["Almaty", "Astana", "Tashkent", "Bishkek"], 1),
    ("Who composed 'Parsifal'?", ["Wagner", "Verdi", "Puccini", "Strauss"], 0),
    ("What is mitochondrial DNA mostly inherited from?", ["Father", "Mother", "Both equally", "Random"], 1),
    ("Who was the first woman to win a Nobel Prize?", ["Curie", "Franklin", "Hodgkin", "Goeppert Mayer"], 0),
    ("Which river is most often cited as the longest?", ["Amazon", "Nile", "Yangtze", "Mississippi"], 1),
    ("What is the pH of lemon juice (roughly)?", ["7", "2", "10", "5"], 1),
    ("Who wrote 'The Trial'?", ["Kafka", "Musil", "Mann", "Hesse"], 0),
    ("What is the largest internal organ by mass (excluding skin)?", ["Brain", "Liver", "Lungs", "Heart"], 1),
    ("Which country has the most time zones (including territories)?", ["Russia", "USA", "France", "UK"], 2),
    ("What is the sum of interior angles of a convex hexagon?", ["540°", "720°", "900°", "360°"], 1),
    ("Who wrote 'Beloved'?", ["Morrison", "Walker", "Angelou", "Hurston"], 0),
    ("What is the escape velocity of Earth (km/s, approximate)?", ["7.9", "11.2", "15.4", "25"], 1),
    ("Which war is associated with the Battle of Gettysburg?", ["Revolutionary", "Civil War", "1812", "Spanish-American"], 1),
    ("What is the capital of Chile?", ["Valparaíso", "Santiago", "Concepción", "Antofagasta"], 1),
    ("Who painted 'The Night Watch'?", ["Vermeer", "Rembrandt", "Hals", "Rubens"], 1),
    ("What is the approximate proton-to-electron mass ratio?", ["~511", "~1,836", "~10,000", "~100"], 1),
]

TE_RUIN: list[tuple[str, list[str], int]] = [
    ("Roughly how old is the observable universe (billions of years)?", ["~10", "~13.8", "~18", "~6"], 1),
    ("About how deep is Challenger Deep in the Mariana Trench (miles)?", ["~3.5", "~7", "~12", "~1"], 1),
    ("How many known moons does Saturn have (as of 2024, commonly cited)?", ["82", "96", "124", "146"], 3),
    ("What percentage of the human genome codes for proteins (roughly)?", ["~50%", "~25%", "~1.5%", "~10%"], 2),
    ("What is the only letter that does not appear in any US state name?", ["X", "Q", "Z", "J"], 1),
    ("Roughly how many muscles does a caterpillar have?", ["~650", "~1,000", "~4,000", "~200"], 2),
    ("What temperature is the same on Fahrenheit and Celsius scales?", ["-40°", "0°", "32°", "100°"], 0),
    ("How many times does the average human heart beat in a lifetime (order)?", ["~1 billion", "~2.5 billion", "~3 billion", "~5 billion"], 2),
    ("What is the approximate Landé g-factor for a free electron?", ["~1", "~2", "~3", "~0.5"], 1),
    ("What is the approximate age of the oldest known Earth rock (billions of years)?", ["~2.5", "~4.4", "~6.0", "~1.0"], 1),
    ("How many countries are in Africa (UN member states, approximate)?", ["44", "48", "54", "60"], 2),
    ("What country has more pyramids than Egypt (commonly cited)?", ["Mexico", "Sudan", "Peru", "Iraq"], 1),
    ("What is the longest US government shutdown in history (days)?", ["21", "35", "42", "16"], 1),
    ("What percentage of Earth's water is fresh (liquid, accessible)?", ["~50%", "~10%", "~3%", "~25%"], 2),
    ("What is the approximate circumference of Earth at the equator (km)?", ["~20,000", "~30,000", "~40,075", "~50,000"], 2),
    ("Roughly what is the average distance from Earth to the Sun (million miles)?", ["~66", "~93", "~120", "~45"], 1),
    ("What is the approximate number of stars in the Milky Way (order)?", ["~100 million", "~100 billion", "~1 trillion", "~10 billion"], 1),
    ("What is the deepest point in Earth's oceans (named trench region)?", ["Puerto Rico Trench", "Mariana Trench", "Java Trench", "Tonga Trench"], 1),
    ("Roughly how many languages are spoken worldwide (order)?", ["~700", "~3,000", "~7,000", "~500"], 2),
    ("What is the approximate distance from Earth to the Moon (miles)?", ["~100,000", "~238,000", "~500,000", "~1,000,000"], 1),
]

# --- America (ta): 10 easy extras + 60 med + 60 hard + 20 ruin (50 US capitals from generator) ---

TA_EASY_EXTRA: list[tuple[str, list[str], int]] = [
    ("Which document begins with 'We the People'?", ["Declaration of Independence", "Constitution", "Bill of Rights", "Articles of Confederation"], 1),
    ("What is the tallest mountain in the contiguous United States?", ["Mount Rainier", "Mount Whitney", "Denali", "Mount Elbert"], 1),
    ("Which river forms much of the U.S.–Mexico border?", ["Mississippi", "Rio Grande", "Colorado", "Columbia"], 1),
    ("What is Nebraska's nickname?", ["The Show-Me State", "The Cornhusker State", "The Buckeye State", "The Sunflower State"], 1),
    ("Which state is called the 'Grand Canyon State'?", ["Utah", "Arizona", "Nevada", "New Mexico"], 1),
    ("Who appears on the U.S. five-dollar bill?", ["Hamilton", "Lincoln", "Jackson", "Grant"], 1),
    ("Which city displays the Liberty Bell?", ["Boston", "Philadelphia", "New York", "Baltimore"], 1),
    ("What is the largest U.S. state by area?", ["Texas", "California", "Alaska", "Montana"], 2),
    ("How many federal holidays does the U.S. observe (common count)?", ["8", "10", "11", "13"], 2),
    ("Which amendment protects freedom of speech?", ["2nd", "1st", "4th", "5th"], 1),
]

TA_MED: list[tuple[str, list[str], int]] = [
    ("Which battle is often called the turning point of the Civil War?", ["Antietam", "Gettysburg", "Shiloh", "Vicksburg"], 1),
    ("What year did the Treaty of Paris end the Revolutionary War?", ["1776", "1781", "1783", "1791"], 2),
    ("Which president bought Louisiana from France?", ["Madison", "Jefferson", "Monroe", "Adams"], 1),
    ("What is the longest river system in the U.S.?", ["Missouri–Mississippi", "Colorado", "Rio Grande", "Yukon"], 0),
    ("Which state was first to ratify the Constitution?", ["Virginia", "Delaware", "Pennsylvania", "Massachusetts"], 1),
    ("Who was the first U.S. president to resign?", ["Johnson", "Nixon", "Clinton", "Ford"], 1),
    ("Which amendment ended Prohibition?", ["18th", "19th", "20th", "21st"], 3),
    ("What year did Hawaii become a state?", ["1956", "1959", "1962", "1965"], 1),
    ("Which national park is home to Old Faithful?", ["Yosemite", "Yellowstone", "Grand Canyon", "Zion"], 1),
    ("What is the capital of Louisiana?", ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"], 1),
    ("Which war is associated with the Rough Riders?", ["Civil War", "Spanish-American War", "WWI", "Mexican-American War"], 1),
    ("Who wrote the Declaration of Independence?", ["Washington", "Jefferson", "Franklin", "Adams"], 1),
    ("What is the smallest U.S. state by area?", ["Delaware", "Rhode Island", "Connecticut", "Hawaii"], 1),
    ("Which city is nicknamed 'Motor City'?", ["Chicago", "Detroit", "Cleveland", "Milwaukee"], 1),
    ("What is the longest hiking trail in the U.S. (namesake)?", ["PCT", "Appalachian Trail", "Continental Divide", "Ice Age Trail"], 1),
    ("Which president is on the dime?", ["Lincoln", "Roosevelt", "Jefferson", "Washington"], 1),
    ("What river runs through the Grand Canyon?", ["Missouri", "Colorado", "Green", "Rio Grande"], 1),
    ("Which state is known as the 'Sunshine State'?", ["California", "Florida", "Arizona", "Texas"], 1),
    ("What year did the U.S. land humans on the Moon?", ["1967", "1969", "1971", "1973"], 1),
    ("Which mountain range runs along the U.S. West Coast?", ["Appalachians", "Rockies", "Sierra Nevada", "Ozarks"], 2),
    ("Who was the first U.S. president born in a hospital?", ["Carter", "Clinton", "Obama", "Biden"], 0),
    ("What is the capital of Ohio?", ["Cleveland", "Columbus", "Cincinnati", "Toledo"], 1),
    ("Which amendment gave women the right to vote?", ["15th", "17th", "19th", "21st"], 2),
    ("What is the largest Great Lake by surface area?", ["Michigan", "Huron", "Superior", "Erie"], 2),
    ("Which city hosted the 1996 Summer Olympics?", ["Los Angeles", "Atlanta", "Chicago", "Houston"], 1),
    ("What is the northernmost U.S. state?", ["Maine", "Washington", "Minnesota", "Alaska"], 3),
    ("Which act created land-grant colleges?", ["Homestead Act", "Morrill Act", "Sherman Act", "Dawes Act"], 1),
    ("Who was Chief Justice during Brown v. Board of Education?", ["Warren", "Marshall", "Douglas", "Black"], 0),
    ("What is the capital of Oregon?", ["Portland", "Salem", "Eugene", "Bend"], 1),
    ("Which state is the 'Volunteer State'?", ["Kentucky", "Tennessee", "Virginia", "North Carolina"], 1),
    ("What year did the U.S. Civil War begin?", ["1859", "1861", "1863", "1865"], 1),
    ("Which president issued the Emancipation Proclamation?", ["Johnson", "Lincoln", "Grant", "Davis"], 1),
    ("What is the capital of Minnesota?", ["Duluth", "Minneapolis", "Saint Paul", "Rochester"], 2),
    ("Which river is nicknamed 'Big Muddy'?", ["Mississippi", "Missouri", "Ohio", "Arkansas"], 1),
    ("What is the largest U.S. state by population?", ["Texas", "New York", "Florida", "California"], 3),
    ("Which city is home to the U.S. Naval Academy?", ["Norfolk", "Annapolis", "Newport", "Charleston"], 1),
    ("What year did the Boston Tea Party occur?", ["1765", "1770", "1773", "1775"], 2),
    ("Which desert covers much of Nevada?", ["Mojave", "Sahara", "Sonoran", "Chihuahuan"], 0),
    ("Who was the only president to serve non-consecutive terms?", ["Taft", "Cleveland", "TRoosevelt", "Wilson"], 1),
    ("What is the capital of Colorado?", ["Boulder", "Denver", "Colorado Springs", "Fort Collins"], 1),
    ("Which state is the 'Pelican State'?", ["Alabama", "Louisiana", "Florida", "Georgia"], 1),
    ("What is the longest U.S. coastline (state)?", ["California", "Florida", "Alaska", "Hawaii"], 2),
    ("Which amendment lowered the voting age to 18?", ["24th", "25th", "26th", "27th"], 2),
    ("What is the capital of Georgia (U.S. state)?", ["Savannah", "Atlanta", "Augusta", "Macon"], 1),
    ("Which city is known as the 'Windy City'?", ["Detroit", "Chicago", "Milwaukee", "Cleveland"], 1),
    ("What year did the stock market crash begin the Great Depression?", ["1925", "1929", "1933", "1937"], 1),
    ("Which president commissioned the Lewis and Clark expedition?", ["Adams", "Jefferson", "Madison", "Monroe"], 1),
    ("What is the capital of Arizona?", ["Tucson", "Phoenix", "Flagstaff", "Mesa"], 1),
    ("Which state is famous for maple syrup production?", ["Vermont", "Maine", "New Hampshire", "All of these"], 3),
    ("What is the name of the U.S. anthem?", ["America the Beautiful", "The Star-Spangled Banner", "God Bless America", "My Country 'Tis of Thee"], 1),
    ("Which river carved the Grand Canyon?", ["Snake", "Colorado", "Green", "Rio Grande"], 1),
    ("What is the capital of Michigan?", ["Detroit", "Grand Rapids", "Lansing", "Ann Arbor"], 2),
    ("Which state is the 'Lone Star State'?", ["Arizona", "Texas", "New Mexico", "Oklahoma"], 1),
    ("What year did the September 11 attacks occur?", ["1999", "2000", "2001", "2002"], 2),
    ("Who was the first Secretary of the Treasury?", ["Jefferson", "Hamilton", "Adams", "Franklin"], 1),
    ("What is the capital of Washington state?", ["Spokane", "Seattle", "Olympia", "Tacoma"], 2),
    ("Which U.S. territory is in the Pacific?", ["Guam", "Puerto Rico", "USVI", "All of these"], 3),
    ("What is the largest national park in the contiguous U.S.?", ["Yellowstone", "Death Valley", "Everglades", "Grand Canyon"], 1),
    ("Which president signed the Civil Rights Act of 1964?", ["Kennedy", "Johnson", "Nixon", "Ford"], 1),
    ("What is the capital of North Carolina?", ["Charlotte", "Raleigh", "Greensboro", "Durham"], 1),
]

TA_HARD: list[tuple[str, list[str], int]] = [
    ("How many amendments are in the Bill of Rights?", ["8", "10", "12", "15"], 1),
    ("Which case established judicial review?", ["Brown v. Board", "Marbury v. Madison", "Roe v. Wade", "Plessy v. Ferguson"], 1),
    ("What year did the Alaska Purchase occur?", ["1848", "1867", "1898", "1912"], 1),
    ("Who was the first female Supreme Court justice?", ["Ginsburg", "O'Connor", "Sotomayor", "Kagan"], 1),
    ("Which president signed the Indian Removal Act?", ["Van Buren", "Jackson", "Harrison", "Tyler"], 1),
    ("What was the first permanent English settlement in North America?", ["Plymouth", "Jamestown", "Roanoke", "St. Augustine"], 1),
    ("Which state was the first to secede in 1860?", ["Georgia", "South Carolina", "Mississippi", "Alabama"], 1),
    ("What is the minimum age to serve in the U.S. Senate?", ["21", "25", "30", "35"], 2),
    ("Which territory did the U.S. buy from Denmark in 1917?", ["Hawaii", "Puerto Rico", "U.S. Virgin Islands", "Guam"], 2),
    ("Who was the Federalist Papers writer besides Hamilton and Madison?", ["Franklin", "Jay", "Jefferson", "Adams"], 1),
    ("What is the length of a U.S. House term (years)?", ["2", "4", "6", "8"], 0),
    ("Which amendment limits presidents to two terms?", ["20th", "22nd", "25th", "27th"], 1),
    ("What year did the War of 1812 end?", ["1812", "1814", "1815", "1818"], 2),
    ("Who was president during the Louisiana Purchase?", ["Adams", "Jefferson", "Madison", "Monroe"], 1),
    ("Which battle ended the War of 1812?", ["New Orleans", "Baltimore", "Plattsburgh", "Tippecanoe"], 0),
    ("What is the capital of South Dakota?", ["Rapid City", "Sioux Falls", "Pierre", "Aberdeen"], 2),
    ("Which president ordered the Emancipation Proclamation?", ["Grant", "Lincoln", "Johnson", "Davis"], 1),
    ("What year did Prohibition begin (18th Amendment)?", ["1915", "1920", "1925", "1930"], 1),
    ("Which state has the most counties?", ["California", "Texas", "Georgia", "Kentucky"], 1),
    ("Who was the youngest elected U.S. president?", ["Clinton", "Kennedy", "Obama", "Roosevelt"], 1),
    ("What is the G.I. Bill formally associated with?", ["WWI", "WWII", "Korean War", "Vietnam War"], 1),
    ("Which amendment protects against double jeopardy?", ["4th", "5th", "6th", "8th"], 1),
    ("What year did the U.S. buy Florida from Spain?", ["1803", "1819", "1848", "1853"], 1),
    ("Who led the Union Army to victory in the Civil War?", ["Sherman", "Grant", "Meade", "McClellan"], 1),
    ("Which city was the U.S. capital before Washington D.C.?", ["Philadelphia", "New York", "Baltimore", "Annapolis"], 0),
    ("What is the only state that borders only one other state?", ["Florida", "Maine", "Rhode Island", "Washington"], 1),
    ("Which president is buried at Arlington National Cemetery?", ["Kennedy", "Taft", "Roosevelt", "Wilson"], 0),
    ("What year did the Gold Rush begin in California?", ["1845", "1848", "1851", "1855"], 1),
    ("Which act created the Interstate Highway System?", ["New Deal", "Federal-Aid Highway Act of 1956", "DOT Act", "EPA Act"], 1),
    ("Who was Chief Justice during the Civil War?", ["Marshall", "Taney", "Chase", "Waite"], 2),
    ("What is the capital of West Virginia?", ["Huntington", "Charleston", "Morgantown", "Wheeling"], 1),
    ("Which amendment abolished poll taxes?", ["14th", "15th", "24th", "26th"], 2),
    ("What year did the U.S. acquire Puerto Rico?", ["1848", "1898", "1917", "1952"], 1),
    ("Who wrote the Monroe Doctrine?", ["Monroe", "Adams", "Clay", "Calhoun"], 1),
    ("Which state is divided into parishes instead of counties?", ["Maryland", "Louisiana", "Virginia", "Vermont"], 1),
    ("What is the maximum number of years someone can serve as president?", ["8", "10", "12", "16"], 1),
    ("Which battle was fought on Christmas 1776?", ["Saratoga", "Trenton", "Princeton", "Yorktown"], 1),
    ("Who was the first Speaker of the House?", ["Madison", "Muhlenberg", "Clay", "Randolph"], 1),
    ("What year did the Articles of Confederation take effect?", ["1776", "1777", "1781", "1787"], 2),
    ("Which president survived an assassination attempt in 1981?", ["Carter", "Reagan", "Bush", "Clinton"], 1),
    ("What is the capital of Vermont?", ["Burlington", "Montpelier", "Rutland", "Brattleboro"], 1),
    ("Which state produces the most corn?", ["Nebraska", "Iowa", "Illinois", "Kansas"], 1),
    ("What year did the U.S. boycott the Moscow Olympics?", ["1976", "1980", "1984", "1988"], 1),
    ("Who was the first African American Supreme Court justice?", ["Marshall", "Thomas", "Thurgood Marshall", "Warren"], 0),
    ("Which river begins in Minnesota and ends in the Gulf?", ["Missouri", "Mississippi", "Ohio", "Tennessee"], 1),
    ("What is the smallest U.S. state capital by population (commonly cited)?", ["Montpelier", "Augusta", "Pierre", "Concord"], 0),
    ("Which president signed the Social Security Act?", ["Hoover", "Roosevelt", "Truman", "Eisenhower"], 1),
    ("What year did the Pentagon open?", ["1939", "1943", "1950", "1955"], 1),
    ("Which amendment guarantees a speedy trial?", ["4th", "5th", "6th", "7th"], 2),
    ("Who was the first U.S. president to live in the White House?", ["Washington", "Adams", "Jefferson", "Madison"], 1),
    ("What is the capital of New York state?", ["New York City", "Buffalo", "Albany", "Rochester"], 2),
    ("Which state has the most national parks?", ["Alaska", "California", "Utah", "Colorado"], 1),
    ("What year did the U.S. leave the Vietnam War (Saigon fell)?", ["1973", "1974", "1975", "1976"], 2),
    ("Who was the longest-serving U.S. president?", ["Washington", "FDR", "Jefferson", "Lincoln"], 1),
    ("Which city was the first U.S. capital under the Constitution?", ["Philadelphia", "New York", "Washington D.C.", "Baltimore"], 1),
    ("What is the capital of Utah?", ["Provo", "Salt Lake City", "Ogden", "St. George"], 1),
    ("Which president is on the $50 bill?", ["Hamilton", "Grant", "Franklin", "Jackson"], 1),
    ("What year did the U.S. invade Panama to remove Noriega?", ["1985", "1989", "1991", "1993"], 1),
    ("Who wrote 'Common Sense'?", ["Jefferson", "Paine", "Franklin", "Henry"], 1),
    ("Which state is entirely above 1,000 ft elevation?", ["Utah", "Colorado", "Wyoming", "All of these"], 1),
]

TA_RUIN: list[tuple[str, list[str], int]] = [
    ("How many electoral votes are needed to win the presidency?", ["250", "270", "300", "335"], 1),
    ("How long is a U.S. senator's term (years)?", ["2", "4", "6", "8"], 2),
    ("Which state has the most House seats (recent apportionment)?", ["Texas", "New York", "Florida", "California"], 3),
    ("What year did the U.S. buy Alaska from Russia?", ["1848", "1867", "1898", "1912"], 1),
    ("How many justices sit on the Supreme Court (traditional full bench)?", ["7", "9", "11", "13"], 1),
    ("About how long is the U.S.–Canada land border (miles)?", ["~3,200", "~5,500", "~8,900", "~2,100"], 1),
    ("How many federal judgeships are in the Supreme Court?", ["5", "7", "9", "11"], 2),
    ("What year did the U.S. Constitution take effect?", ["1776", "1781", "1788", "1791"], 2),
    ("Which state was last admitted before Alaska and Hawaii?", ["New Mexico", "Arizona", "Oklahoma", "Texas"], 1),
    ("How many stripes on the U.S. flag?", ["11", "13", "15", "50"], 1),
    ("What is the length of a presidential term (years)?", ["2", "4", "6", "8"], 1),
    ("Which amendment repealed Prohibition?", ["18th", "19th", "20th", "21st"], 3),
    ("How many voting members in the House of Representatives?", ["50", "100", "435", "538"], 2),
    ("What year did the U.S. Civil Rights Act pass?", ["1960", "1964", "1968", "1972"], 1),
    ("Which state has the lowest population?", ["Vermont", "Wyoming", "Alaska", "North Dakota"], 1),
    ("How many amendments does the Constitution have (ratified)?", ["25", "27", "30", "33"], 1),
    ("What is the minimum age to be president?", ["25", "30", "35", "40"], 2),
    ("Which city is the geographic center of the contiguous U.S. (commonly cited)?", ["Lebanon, KS", "St. Louis", "Omaha", "Denver"], 0),
    ("How many time zones does the continental U.S. span?", ["2", "3", "4", "5"], 2),
    ("What year did the U.S. leave the gold standard (Nixon shock)?", ["1968", "1971", "1974", "1980"], 1),
]

# --- World (tw): 10 easy extras + 60 med + 60 hard + 20 ruin (50 world capitals from generator) ---

TW_EASY_EXTRA: list[tuple[str, list[str], int]] = [
    ("Which ocean is the largest?", ["Atlantic", "Indian", "Arctic", "Pacific"], 3),
    ("What is the longest mountain range in the world?", ["Rockies", "Andes", "Himalayas", "Alps"], 1),
    ("Which country is both in Europe and Asia?", ["Egypt", "Turkey", "Morocco", "Spain"], 1),
    ("What river runs through Paris?", ["Thames", "Seine", "Danube", "Rhine"], 1),
    ("Which country is shaped like a boot?", ["Greece", "Italy", "Chile", "Norway"], 1),
    ("What is the largest country by area?", ["China", "Canada", "USA", "Russia"], 3),
    ("Which African country has the largest population?", ["Kenya", "South Africa", "Nigeria", "Egypt"], 2),
    ("What is the official language of Brazil?", ["Spanish", "Portuguese", "English", "French"], 1),
    ("Which city hosted the 2012 Summer Olympics?", ["Beijing", "London", "Athens", "Sydney"], 1),
    ("What is the smallest country in the world?", ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], 1),
]

TW_MED: list[tuple[str, list[str], int]] = [
    ("Which city is called the 'Eternal City'?", ["Athens", "Rome", "Cairo", "Istanbul"], 1),
    ("What is the deepest lake in the world by maximum depth?", ["Superior", "Baikal", "Tanganyika", "Caspian"], 1),
    ("Which strait separates Europe from Africa?", ["Bosporus", "Gibraltar", "Hormuz", "Malacca"], 1),
    ("Which EU country has the largest population?", ["France", "Germany", "Italy", "Spain"], 1),
    ("What is the driest non-polar desert often cited?", ["Sahara", "Atacama", "Gobi", "Arabian"], 1),
    ("Which river is sacred to Hindus?", ["Amazon", "Ganges", "Nile", "Yangtze"], 1),
    ("What is the tallest mountain in Africa?", ["K2", "Kenya", "Kilimanjaro", "Atlas"], 2),
    ("Which two countries share the longest international border?", ["Russia–China", "USA–Canada", "India–China", "Chile–Argentina"], 1),
    ("What is the largest island in the Mediterranean?", ["Crete", "Sicily", "Sardinia", "Cyprus"], 1),
    ("Which country was never colonized by Europeans (often cited)?", ["Liberia", "Ethiopia", "Ghana", "Kenya"], 1),
    ("What is the capital of South Africa (executive)?", ["Johannesburg", "Cape Town", "Pretoria", "Durban"], 2),
    ("Which sea has the highest salinity?", ["Red Sea", "Dead Sea", "Mediterranean", "Black Sea"], 1),
    ("What is the largest country in South America?", ["Argentina", "Brazil", "Colombia", "Peru"], 1),
    ("Which river flows through Vienna?", ["Rhine", "Danube", "Elbe", "Po"], 1),
    ("What is the capital of Morocco?", ["Casablanca", "Rabat", "Marrakech", "Fez"], 1),
    ("Which Asian country is known as the 'Land of the Rising Sun'?", ["China", "Japan", "Korea", "Thailand"], 1),
    ("What is the largest archipelago country by island count (often cited)?", ["Japan", "Philippines", "Sweden", "Indonesia"], 3),
    ("Which desert covers much of northern Africa?", ["Gobi", "Sahara", "Kalahari", "Mojave"], 1),
    ("What is the capital of Vietnam?", ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"], 1),
    ("Which ocean is off the east coast of Africa?", ["Atlantic", "Indian", "Pacific", "Southern"], 1),
    ("What is the largest bay in the world by area?", ["Hudson Bay", "Bay of Bengal", "Gulf of Mexico", "Baffin Bay"], 1),
    ("Which country is landlocked in South America?", ["Uruguay", "Paraguay", "Ecuador", "Guyana"], 1),
    ("What is the capital of Scotland?", ["Glasgow", "Edinburgh", "Aberdeen", "Dundee"], 1),
    ("Which river is the longest in Europe?", ["Danube", "Volga", "Rhine", "Seine"], 1),
    ("What is the most populous island in the world?", ["Honshu", "Java", "Luzon", "Great Britain"], 1),
    ("Which country borders both France and Spain?", ["Italy", "Andorra", "Switzerland", "Portugal"], 1),
    ("What is the capital of Nigeria?", ["Lagos", "Abuja", "Kano", "Ibadan"], 1),
    ("Which sea separates the UK and Scandinavia?", ["Baltic", "North Sea", "Irish Sea", "Mediterranean"], 1),
    ("What is the largest lake in South America?", ["Titicaca", "Maracaibo", "General Carrera", "Argentino"], 1),
    ("Which country is famous for fjords?", ["Sweden", "Norway", "Finland", "Iceland"], 1),
    ("What is the capital of Peru?", ["Cusco", "Lima", "Arequipa", "Trujillo"], 1),
    ("Which river crosses the equator twice?", ["Amazon", "Congo", "Nile", "Orinoco"], 1),
    ("What is the driest inhabited continent?", ["Africa", "Australia", "Asia", "Antarctica"], 1),
    ("Which city is the financial hub of Germany?", ["Munich", "Frankfurt", "Hamburg", "Cologne"], 1),
    ("What is the capital of New Zealand?", ["Auckland", "Wellington", "Christchurch", "Queenstown"], 1),
    ("Which country has the most time zones (including territories)?", ["Russia", "USA", "France", "UK"], 2),
    ("What is the largest island in Japan?", ["Hokkaido", "Honshu", "Kyushu", "Shikoku"], 1),
    ("Which African Great Lake is shared by four countries?", ["Victoria", "Tanganyika", "Malawi", "Turkana"], 1),
    ("What is the capital of Cuba?", ["Santiago", "Havana", "Varadero", "Holguín"], 1),
    ("Which strait connects the Mediterranean and Atlantic?", ["Bosporus", "Gibraltar", "Hormuz", "Bering"], 1),
    ("What is the largest country in the Middle East by area?", ["Iran", "Saudi Arabia", "Iraq", "Turkey"], 1),
    ("Which river runs through Baghdad?", ["Jordan", "Tigris", "Euphrates", "Both Tigris and Euphrates nearby"], 3),
    ("What is the capital of Kenya?", ["Mombasa", "Nairobi", "Kisumu", "Nakuru"], 1),
    ("Which country is the 'Emerald Isle'?", ["Scotland", "Ireland", "Wales", "Iceland"], 1),
    ("What is the largest city in Australia?", ["Melbourne", "Sydney", "Brisbane", "Perth"], 1),
    ("Which desert is in southern Africa?", ["Sahara", "Kalahari", "Namib", "Gobi"], 1),
    ("What is the capital of Greece?", ["Thessaloniki", "Athens", "Patras", "Heraklion"], 1),
    ("Which mountain range separates Europe from Asia (partially)?", ["Alps", "Urals", "Caucasus", "Pyrenees"], 1),
    ("What is the official language of Iran?", ["Arabic", "Turkish", "Farsi", "Urdu"], 2),
    ("Which country is home to Angkor Wat?", ["Thailand", "Vietnam", "Cambodia", "Laos"], 2),
    ("What is the longest river in Europe?", ["Rhine", "Danube", "Volga", "Elbe"], 2),
    ("Which island nation is off the southeast coast of India?", ["Maldives", "Sri Lanka", "Mauritius", "Seychelles"], 1),
    ("What is the capital of Portugal?", ["Porto", "Lisbon", "Braga", "Coimbra"], 1),
    ("Which sea is between Italy and the Balkans?", ["Black Sea", "Adriatic Sea", "Aegean Sea", "Tyrrhenian Sea"], 1),
    ("What is the largest country in Africa by area?", ["Democratic Republic of the Congo", "Sudan", "Algeria", "Libya"], 2),
    ("Which river is important to ancient Mesopotamia?", ["Indus", "Nile", "Tigris/Euphrates", "Yangtze"], 2),
    ("What is the capital of Switzerland?", ["Zurich", "Geneva", "Bern", "Basel"], 2),
    ("Which country is both in the EU and not using the euro (commonly cited)?", ["Poland", "Sweden", "Denmark", "All can apply"], 3),
    ("What is the largest island in the Caribbean?", ["Jamaica", "Cuba", "Hispaniola", "Puerto Rico"], 1),
    ("Which ocean surrounds the Maldives?", ["Atlantic", "Indian", "Pacific", "Southern"], 1),
]

TW_HARD: list[tuple[str, list[str], int]] = [
    ("Which country has the most islands (commonly cited)?", ["Philippines", "Indonesia", "Sweden", "Japan"], 2),
    ("What is the southernmost capital city in the world?", ["Cape Town", "Wellington", "Canberra", "Santiago"], 1),
    ("Which landlocked country is the largest by area?", ["Mongolia", "Kazakhstan", "Chad", "Niger"], 1),
    ("What is the highest capital city in the world?", ["Quito", "La Paz", "Bogotá", "Addis Ababa"], 1),
    ("Which African country has the most pyramids after Sudan?", ["Egypt", "Ethiopia", "Nigeria", "Libya"], 0),
    ("What is the most densely populated country?", ["Bangladesh", "Singapore", "Monaco", "Malta"], 2),
    ("Which river forms part of the border between the U.S. and Mexico?", ["Colorado", "Rio Grande", "Pecos", "Gila"], 1),
    ("What is the capital of Kazakhstan?", ["Almaty", "Astana", "Shymkent", "Karaganda"], 1),
    ("Which country has a flag with a dragon?", ["China", "Bhutan", "Wales", "Nepal"], 1),
    ("What is the oldest continuously operating university (often cited)?", ["Oxford", "Bologna", "al-Qarawiyyin", "Al-Azhar"], 2),
    ("Which sea is the saltiest?", ["Red Sea", "Dead Sea", "Mediterranean", "Arabian Sea"], 1),
    ("What is the largest island in the world?", ["Borneo", "Greenland", "New Guinea", "Madagascar"], 1),
    ("Which country borders the most other countries?", ["Russia", "China", "Brazil", "Germany"], 1),
    ("What is the capital of Mongolia?", ["Ulaanbaatar", "Astana", "Tashkent", "Bishkek"], 0),
    ("Which waterfall has the largest sheet of falling water?", ["Niagara", "Victoria", "Iguazu", "Angel Falls"], 1),
    ("What is the largest metro area in the world (often cited)?", ["Tokyo", "Delhi", "Shanghai", "São Paulo"], 0),
    ("Which country is entirely south of the equator?", ["Indonesia", "Australia", "Brazil", "Kenya"], 1),
    ("What is the capital of Bhutan?", ["Thimphu", "Kathmandu", "Paro", "Punakha"], 0),
    ("Which strait is between Alaska and Russia?", ["Hormuz", "Bering", "Taiwan", "Magellan"], 1),
    ("What is the largest atoll in the world?", ["Kwajalein", "Great Chagos Bank", "Funafuti", "Aldabra"], 1),
    ("Which country has the most volcanoes?", ["Japan", "Indonesia", "Chile", "Iceland"], 1),
    ("What is the capital of Latvia?", ["Tallinn", "Riga", "Vilnius", "Minsk"], 1),
    ("Which desert is partly in Chile?", ["Sahara", "Atacama", "Kalahari", "Mojave"], 1),
    ("What is the longest river in Asia?", ["Yangtze", "Yellow", "Mekong", "Ganges"], 0),
    ("Which country is the largest in Oceania?", ["New Zealand", "Papua New Guinea", "Australia", "Fiji"], 2),
    ("What is the capital of Slovakia?", ["Prague", "Bratislava", "Budapest", "Vienna"], 1),
    ("Which sea is landlocked except for narrow outlets?", ["Red Sea", "Caspian Sea", "Black Sea", "Baltic Sea"], 1),
    ("What is the largest city in Africa?", ["Johannesburg", "Lagos", "Cairo", "Kinshasa"], 1),
    ("Which country is on both the Atlantic and Indian Oceans?", ["Angola", "South Africa", "Namibia", "Mozambique"], 1),
    ("What is the capital of Estonia?", ["Riga", "Tallinn", "Vilnius", "Helsinki"], 1),
    ("Which mountain is tallest outside Asia?", ["Denali", "Aconcagua", "Kilimanjaro", "Elbrus"], 1),
    ("What is the smallest EU country by area?", ["Luxembourg", "Malta", "Cyprus", "Slovenia"], 1),
    ("Which river flows through St. Petersburg?", ["Volga", "Neva", "Dnieper", "Don"], 1),
    ("What is the capital of Slovenia?", ["Zagreb", "Ljubljana", "Belgrade", "Sarajevo"], 1),
    ("Which country is Suriname's neighbor to the east?", ["Brazil", "Guyana", "French Guiana", "Venezuela"], 2),
    ("What is the largest salt flat?", ["Bonneville", "Salar de Uyuni", "Etosha", "Chott el Djerid"], 1),
    ("Which island is split between Indonesia and Papua New Guinea?", ["Sumatra", "Borneo", "New Guinea", "Sulawesi"], 2),
    ("What is the capital of Oman?", ["Dubai", "Muscat", "Doha", "Abu Dhabi"], 1),
    ("Which sea freezes seasonally around Siberia?", ["Baltic", "Laptev Sea", "Mediterranean", "Caribbean"], 1),
    ("What is the most visited city internationally (often cited)?", ["Paris", "Bangkok", "London", "Dubai"], 1),
    ("Which country is Surrounded by Italy?", ["San Marino", "Vatican City", "Both", "Monaco"], 2),
    ("What is the capital of Qatar?", ["Dubai", "Doha", "Manama", "Kuwait City"], 1),
    ("Which river is important to ancient Egypt?", ["Tigris", "Nile", "Jordan", "Congo"], 1),
    ("What is the largest island in the Mediterranean?", ["Sicily", "Sardinia", "Cyprus", "Crete"], 0),
    ("Which country uses the peso named after a bird?", ["Mexico", "Chile", "Colombia", "Philippines"], 1),
    ("What is the capital of Serbia?", ["Split", "Belgrade", "Sarajevo", "Skopje"], 1),
    ("Which African country has the most UNESCO sites (often cited)?", ["Egypt", "Morocco", "Ethiopia", "South Africa"], 0),
    ("What is the deepest point in the Atlantic?", ["Puerto Rico Trench", "Milwaukee Deep", "Java Trench", "Sunda Trench"], 1),
    ("Which country is the 'Pearl of Africa'?", ["Kenya", "Uganda", "Rwanda", "Tanzania"], 1),
    ("What is the capital of North Macedonia?", ["Skopje", "Tirana", "Pristina", "Sofia"], 0),
    ("Which strait is between Sumatra and Malaysia?", ["Sunda", "Malacca", "Lombok", "Bali"], 1),
    ("What is the largest lake in Japan?", ["Biwa", "Toya", "Chūzenji", "Inawashiro"], 0),
    ("Which country is the world's largest cocoa producer?", ["Ghana", "Ivory Coast", "Nigeria", "Brazil"], 1),
    ("What is the capital of Rwanda?", ["Kigali", "Nairobi", "Kampala", "Bujumbura"], 0),
    ("Which river flows through Prague?", ["Danube", "Vltava", "Elbe", "Oder"], 1),
    ("What is the largest island in Norway?", ["Senja", "Hinnøya", "Spitsbergen", "Langøya"], 1),
    ("Which country borders Lake Victoria?", ["Only Tanzania", "Only Kenya", "Kenya, Tanzania, Uganda", "Only Uganda"], 2),
    ("What is the capital of Laos?", ["Phnom Penh", "Vientiane", "Hanoi", "Yangon"], 1),
    ("Which oceanic trench is the deepest on Earth?", ["Puerto Rico Trench", "Mariana Trench", "Java Trench", "Tonga Trench"], 1),
    ("Which country lies entirely within the Alps?", ["Switzerland", "Liechtenstein", "Austria", "Slovenia"], 1),
]

TW_RUIN: list[tuple[str, list[str], int]] = [
    ("How many countries are UN member states (approximate, 2020s)?", ["~150", "~193", "~210", "~250"], 1),
    ("What is India's approximate population (billions, 2020s)?", ["~1.0", "~1.4", "~1.8", "~2.2"], 1),
    ("What percentage of Earth's surface does the Pacific Ocean cover?", ["~20%", "~25%", "~30%", "~46%"], 3),
    ("Which country has more pyramids than Egypt (commonly cited)?", ["Mexico", "Sudan", "Peru", "Iraq"], 1),
    ("What is the only national flag that is not rectangular?", ["Switzerland", "Vatican City", "Nepal", "Bhutan"], 2),
    ("How many time zones does Russia span (approximate)?", ["5", "7", "9", "11"], 3),
    ("What is the length of the equator (km, approximate)?", ["~30,000", "~40,075", "~50,000", "~60,000"], 1),
    ("Which country has the longest coastline?", ["Indonesia", "Canada", "Russia", "Australia"], 1),
    ("What is the population of Vatican City (order)?", ["~500", "~1,000", "~5,000", "~50,000"], 1),
    ("How many countries are in Africa (UN members, approximate)?", ["44", "48", "54", "60"], 2),
    ("What is the distance around Earth at the equator (miles, approximate)?", ["~15,000", "~24,901", "~30,000", "~40,000"], 1),
    ("Which country is the flattest (often cited)?", ["Australia", "Maldives", "Bangladesh", "Netherlands"], 1),
    ("What is the largest metro population in India?", ["Mumbai", "Delhi", "Bangalore", "Kolkata"], 1),
    ("Which country has the most official languages?", ["India", "South Africa", "Switzerland", "Bolivia"], 1),
    ("What is the lowest point on Earth's land surface (not underwater)?", ["Turpan", "Dead Sea shore", "Danakil", "Death Valley"], 1),
    ("How many islands does Indonesia have (order)?", ["~1,000", "~7,000", "~17,000", "~50,000"], 2),
    ("What is the longest border between two countries?", ["USA–Canada", "Russia–Kazakhstan", "India–Bangladesh", "China–Mongolia"], 0),
    ("Which capital is closest to the geographic North Pole?", ["Reykjavik", "Helsinki", "Oslo", "Nuuk"], 3),
    ("What is the smallest country by population (UN member)?", ["Nauru", "Tuvalu", "Palau", "San Marino"], 0),
    ("Which river discharges the most water to the ocean?", ["Nile", "Amazon", "Congo", "Yangtze"], 1),
]

TG_EASY: list[tuple[str, list[str], int]] = [
    ("What gas do plants take in for photosynthesis?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], 2),
    ("What is the center of an atom called?", ["Electron cloud", "Nucleus", "Shell", "Orbital"], 1),
    ("How many legs does a spider have?", ["6", "8", "10", "12"], 1),
    ("What is the largest planet?", ["Earth", "Jupiter", "Saturn", "Neptune"], 1),
    ("What vitamin do you get from sunlight on skin?", ["A", "B12", "C", "D"], 3),
    ("What is H2O?", ["Salt", "Water", "Hydrogen peroxide", "Sugar"], 1),
    ("Which organ pumps blood?", ["Liver", "Heart", "Lung", "Stomach"], 1),
    ("What is the chemical symbol for oxygen?", ["O", "Ox", "Om", "Og"], 0),
    ("What type of animal is a whale?", ["Fish", "Mammal", "Reptile", "Amphibian"], 1),
    ("What do plants need besides water and sunlight?", ["Gold", "CO₂", "Helium", "Neon"], 1),
    ("What is the closest star to Earth?", ["Polaris", "The Sun", "Sirius", "Alpha Centauri"], 1),
    ("How many wings does a butterfly have?", ["2", "4", "6", "8"], 1),
    ("What is the state of matter with a fixed volume but no fixed shape?", ["Solid", "Liquid", "Gas", "Plasma"], 1),
    ("What is the hardest natural material?", ["Gold", "Diamond", "Iron", "Silver"], 1),
    ("Which planet is known as the Red Planet?", ["Venus", "Mars", "Jupiter", "Mercury"], 1),
    ("What is the main gas we breathe in?", ["Pure oxygen", "Mostly nitrogen", "Mostly CO₂", "Helium"], 1),
    ("What is the boiling point of water in Celsius?", ["90°C", "100°C", "212°C", "0°C"], 1),
    ("What is the chemical symbol for iron?", ["Ir", "Fe", "F", "In"], 1),
    ("Which blood cells carry oxygen?", ["White blood cells", "Red blood cells", "Platelets", "Plasma"], 1),
    ("What is the largest organ of the body?", ["Liver", "Skin", "Brain", "Lungs"], 1),
    ("What kind of energy does food provide?", ["Nuclear", "Chemical", "Electrical", "Magnetic"], 1),
    ("What is the process plants use to make food?", ["Respiration", "Photosynthesis", "Digestion", "Fermentation"], 1),
    ("How many chambers does a human heart have?", ["2", "3", "4", "5"], 2),
    ("What is frozen carbon dioxide called?", ["Ice", "Dry ice", "Snow", "Frost"], 1),
    ("What is the speed of sound in air (approx., mph)?", ["100", "343", "767", "1,000"], 2),
    ("What is the chemical symbol for sodium?", ["So", "Na", "S", "Nd"], 1),
    ("Which planet is known for rings?", ["Jupiter", "Saturn", "Neptune", "Uranus"], 1),
    ("What is the study of animals called?", ["Botany", "Zoology", "Geology", "Ecology"], 1),
    ("What is the positive particle in an atom's nucleus?", ["Electron", "Proton", "Neutron", "Photon"], 1),
    ("What is the main component of natural gas?", ["Oxygen", "Methane", "Nitrogen", "CO₂"], 1),
    ("How many bones in an adult human (approx.)?", ["186", "206", "256", "300"], 1),
    ("What is the largest planet in our solar system?", ["Saturn", "Jupiter", "Neptune", "Uranus"], 1),
    ("What do bees pollinate?", ["Only trees", "Flowering plants", "Only grass", "Only crops"], 1),
    ("What is the chemical symbol for carbon?", ["Ca", "C", "Co", "Cr"], 1),
    ("Which gas makes balloons float (non-toxic party type)?", ["Oxygen", "Helium", "Hydrogen", "Nitrogen"], 1),
    ("What is the nearest planet to Earth (on average)?", ["Mars", "Venus", "Mercury", "Moon"], 1),
    ("What is the basic unit of life?", ["Atom", "Molecule", "Cell", "Tissue"], 2),
    ("What is the chemical formula for water?", ["CO2", "H2O", "NaCl", "O2"], 1),
    ("Which organ filters blood?", ["Heart", "Kidneys", "Lungs", "Stomach"], 1),
    ("What is the largest moon of Earth?", ["Phobos", "The Moon", "Europa", "Titan"], 1),
    ("What is the main gas released by human respiration?", ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], 1),
    ("What is the chemical symbol for gold?", ["Go", "Au", "Ag", "Gd"], 1),
    ("Which sense detects light?", ["Hearing", "Sight", "Smell", "Taste"], 1),
    ("What is the center of the solar system?", ["Earth", "Moon", "Sun", "Jupiter"], 2),
    ("What is the state of matter in the Sun's core?", ["Solid", "Liquid", "Gas", "Plasma"], 3),
    ("How many eyes does a typical human have?", ["1", "2", "3", "4"], 1),
    ("What is the chemical symbol for silver?", ["Si", "Ag", "Au", "Sr"], 1),
    ("Which planet is the hottest on average?", ["Mercury", "Venus", "Mars", "Jupiter"], 1),
    ("What is the main component of air we exhale?", ["Pure oxygen", "Mostly nitrogen", "Mostly CO₂ only", "Helium"], 1),
    ("What is the study of fungi called?", ["Botany", "Mycology", "Virology", "Entomology"], 1),
    ("What particle orbits the nucleus?", ["Proton", "Neutron", "Electron", "Positron"], 2),
    ("What is the largest bone in the human body?", ["Humerus", "Femur", "Tibia", "Skull"], 1),
    ("What is the chemical symbol for copper?", ["Co", "Cu", "Cp", "Cr"], 1),
    ("Which planet has the Great Red Spot?", ["Earth", "Mars", "Jupiter", "Saturn"], 2),
    ("What is the main gas in the Sun?", ["Oxygen", "Hydrogen", "Helium", "Carbon"], 1),
    ("What is the process of liquid to gas at the surface?", ["Freezing", "Evaporation", "Sublimation", "Deposition"], 1),
    ("How many teeth does an adult human usually have (with wisdom teeth)?", ["28", "30", "32", "36"], 2),
    ("What is the chemical symbol for potassium?", ["P", "K", "Pt", "Po"], 1),
    ("Which organ produces insulin?", ["Liver", "Pancreas", "Kidney", "Gallbladder"], 1),
    ("What is the largest mammal?", ["Elephant", "Blue whale", "Giraffe", "Orca"], 1),
]

TG_MED: list[tuple[str, list[str], int]] = [
    ("What is the SI unit of electric current?", ["Volt", "Ampere", "Watt", "Ohm"], 1),
    ("What is absolute zero in Celsius?", ["-100°C", "-273.15°C", "0°C", "-460°C"], 1),
    ("What type of bond shares electrons?", ["Ionic", "Covalent", "Metallic", "Hydrogen"], 1),
    ("What is Newton's third law?", ["F = ma", "Inertia", "Equal and opposite reaction", "Energy conservation"], 2),
    ("What is the study of heredity?", ["Ecology", "Genetics", "Geology", "Meteorology"], 1),
    ("What particle has no charge?", ["Proton", "Electron", "Neutron", "Positron"], 2),
    ("What is the main gas produced in complete combustion of hydrocarbons?", ["CO", "CO₂", "O₂", "N₂"], 1),
    ("How long does light take to reach Earth from the Sun (approx.)?", ["~1 min", "~8 min", "~1 hour", "~1 sec"], 1),
    ("What is the universal donor blood type?", ["AB+", "O-", "A-", "B+"], 1),
    ("What is the chemical formula for glucose?", ["CH4", "C6H12O6", "CO2", "H2O"], 1),
    ("Who proposed general relativity?", ["Newton", "Einstein", "Hawking", "Bohr"], 1),
    ("What is the Richter scale used for?", ["Wind", "Earthquakes", "Sound", "Temperature"], 1),
    ("What is the largest organ inside the body (not skin)?", ["Brain", "Liver", "Lungs", "Heart"], 1),
    ("What is the pH of pure water?", ["6", "7", "8", "14"], 1),
    ("What process splits a cell into two identical daughter cells?", ["Meiosis", "Mitosis", "Osmosis", "Diffusion"], 1),
    ("What is the most abundant element in the universe?", ["Oxygen", "Carbon", "Hydrogen", "Helium"], 2),
    ("What is the chemical formula for methane?", ["CH3", "CH4", "C2H6", "CO"], 1),
    ("What is the speed of light in vacuum (approx., m/s)?", ["150,000,000", "299,792,458", "400,000,000", "1,000,000"], 1),
    ("What is the term for animals active at dawn and dusk?", ["Nocturnal", "Diurnal", "Crepuscular", "Arboreal"], 2),
    ("What is Avogadro's number (order)?", ["~10⁸", "~6×10²³", "~10¹⁵", "~10³⁰"], 1),
    ("What is the half-life of Carbon-14 (years)?", ["~1,000", "~5,730", "~50,000", "~100"], 1),
    ("What organelle is the primary site of protein synthesis?", ["Mitochondria", "Ribosome", "Lysosome", "Golgi"], 1),
    ("What is the chemical symbol for lead?", ["Le", "Pb", "Pd", "Pt"], 1),
    ("What law states gas pressure × volume is constant at constant temperature?", ["Charles", "Boyle", "Gay-Lussac", "Dalton"], 1),
    ("What is the largest species of living fish?", ["Great white", "Whale shark", "Blue whale", "Giant squid"], 1),
    ("What is the term for water loss through plant stomata?", ["Photosynthesis", "Transpiration", "Respiration", "Osmosis"], 1),
    ("What is the chemical formula for table salt?", ["Na2O", "NaCl", "KCl", "CaCl2"], 1),
    ("What is the derivative of sin(x)?", ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"], 0),
    ("What is the unit of force?", ["Joule", "Newton", "Watt", "Pascal"], 1),
    ("What is the atomic number of carbon?", ["4", "6", "8", "12"], 1),
    ("What is the process by which DNA makes RNA?", ["Translation", "Transcription", "Replication", "Mitosis"], 1),
    ("What is the most electronegative element?", ["Chlorine", "Oxygen", "Fluorine", "Nitrogen"], 2),
    ("What is the name for a positively charged ion?", ["Anion", "Cation", "Isotope", "Radical"], 1),
    ("What is the largest moon of Saturn?", ["Rhea", "Titan", "Enceladus", "Iapetus"], 1),
    ("What is the study of insects?", ["Ornithology", "Entomology", "Herpetology", "Ichthyology"], 1),
    ("What is the chemical symbol for tungsten?", ["T", "W", "Tu", "Tg"], 1),
    ("What is the first step of cellular respiration?", ["Krebs cycle", "Glycolysis", "Electron transport", "Fermentation"], 1),
    ("What is the approximate age of the universe (billions of years)?", ["~4.5", "~13.8", "~50", "~100"], 1),
    ("What is the densest naturally occurring element?", ["Lead", "Osmium", "Uranium", "Gold"], 1),
    ("What is the term for same atomic number, different mass?", ["Isomer", "Isotope", "Ion", "Allotrope"], 1),
    ("What is the SI unit of energy?", ["Newton", "Joule", "Watt", "Pascal"], 1),
    ("What is the pH of a strong acid typically?", ["1–2", "7", "10–11", "14"], 0),
    ("What gas do humans need to survive breathing?", ["Nitrogen only", "Oxygen", "Carbon dioxide", "Helium"], 1),
    ("What is the powerhouse of photosynthesis in plants?", ["Roots", "Chloroplasts", "Mitochondria", "Vacuole"], 1),
    ("What is the chemical symbol for mercury?", ["Mg", "Hg", "Me", "Mr"], 1),
    ("What is the normal human body temperature (°C)?", ["35°C", "37°C", "40°C", "42°C"], 1),
    ("What is the term for animals that eat only plants?", ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], 1),
    ("What is the largest internal organ by mass?", ["Brain", "Liver", "Lungs", "Heart"], 1),
    ("What is the chemical formula for carbon dioxide?", ["CO", "CO2", "C2O", "O2"], 1),
    ("What is the speed of sound in air (m/s, approx.)?", ["150", "343", "500", "1,000"], 1),
    ("What is the term for a change from solid directly to gas?", ["Melting", "Sublimation", "Deposition", "Evaporation"], 1),
    ("What is the atomic mass unit based on?", ["Hydrogen-1", "Carbon-12", "Oxygen-16", "Sodium-23"], 1),
    ("What is the largest bone in the arm?", ["Radius", "Humerus", "Ulna", "Carpal"], 1),
    ("What is the chemical symbol for tin?", ["Ti", "Sn", "Tin", "Sr"], 1),
    ("What is the term for blood cell fragments that clot?", ["Red cells", "White cells", "Platelets", "Plasma"], 2),
    ("What is the main component of natural rubber?", ["Silicon", "Isoprene polymers", "Cellulose", "Starch"], 1),
    ("What is the escape velocity of Earth (km/s, approx.)?", ["7.9", "11.2", "15", "25"], 1),
    ("What is the chemical formula for sulfuric acid?", ["H2SO3", "H2SO4", "HSO4", "H2S"], 1),
    ("What is the term for a catalyst in biology?", ["Hormone", "Enzyme", "Antibody", "Neurotransmitter"], 1),
    ("What is the largest moon of Jupiter?", ["Io", "Europa", "Ganymede", "Callisto"], 2),
]

TG_HARD: list[tuple[str, list[str], int]] = [
    ("What is the Heisenberg Uncertainty Principle about?", ["Energy conservation", "Position and momentum", "Wave-particle duality", "Mass-energy"], 1),
    ("What is the half-life of Uranium-238 (order, years)?", ["~700 million", "~4.5 billion", "~10,000", "~100"], 1),
    ("What is the name of the discontinuity between mantle and outer core?", ["Mohorovičić", "Gutenberg", "Lehmann", "Conrad"], 1),
    ("What is the approximate age of Earth (years)?", ["~2.5 billion", "~4.5 billion", "~6 billion", "~10 billion"], 1),
    ("What is the derivative of ln(x)?", ["x", "1/x", "e^x", "ln(x)"], 1),
    ("What is the spin quantum number for an electron?", ["0", "1/2", "1", "2"], 1),
    ("What is the primary pigment in plants?", ["Carotene", "Chlorophyll", "Anthocyanin", "Xanthophyll"], 1),
    ("What is the bond angle in a tetrahedral molecule?", ["90°", "109.5°", "120°", "180°"], 1),
    ("What is the most common isotope of hydrogen?", ["Deuterium", "Protium", "Tritium", "Quadium"], 1),
    ("What is the name of the immune cells that recognize antigens?", ["Erythrocytes", "Lymphocytes", "Platelets", "Osteocytes"], 1),
    ("What is the approximate percentage of oxygen in Earth's crust by mass?", ["~1%", "~10%", "~46%", "~70%"], 2),
    ("What is the term for the minimum energy to escape a metal's surface (electrons)?", ["Ionization energy", "Work function", "Band gap", "Fermi energy"], 1),
    ("What is the pKa of water at 25°C (approx.)?", ["7", "14", "15.7", "0"], 2),
    ("What is the largest organelle in most plant cells?", ["Nucleus", "Vacuole", "Mitochondria", "Chloroplast"], 1),
    ("What is the speed of light in miles per second (approx.)?", ["86,000", "186,000", "246,000", "300,000"], 1),
    ("What is the term for RNA that carries amino acids?", ["mRNA", "tRNA", "rRNA", "snRNA"], 1),
    ("What is the approximate bond energy of H–H (kJ/mol)?", ["~200", "~436", "~800", "~50"], 1),
    ("What is the name of the cycle that produces ATP in mitochondria?", ["Calvin cycle", "Krebs cycle", "Citric acid cycle", "Both Krebs and citric acid"], 3),
    ("What is the approximate number of bones in a newborn baby?", ["206", "270", "300", "350"], 1),
    ("What is the term for a solution with pH less than 7?", ["Basic", "Acidic", "Neutral", "Buffered"], 1),
    ("What is the quantum number that describes orbital shape?", ["n", "l", "ml", "ms"], 1),
    ("What is the main gas in Venus's atmosphere?", ["Oxygen", "Nitrogen", "Carbon dioxide", "Methane"], 2),
    ("What is the approximate density of water (kg/m³)?", ["100", "1,000", "10,000", "100,000"], 1),
    ("What is the term for a catalyst that speeds biological reactions?", ["Hormone", "Enzyme", "Vitamin", "Coenzyme"], 1),
    ("What is the half-life of Iodine-131 (approx., days)?", ["~8 days", "~30 days", "~1 year", "~100 days"], 0),
    ("What is the largest moon of Neptune?", ["Proteus", "Triton", "Nereid", "Larissa"], 1),
    ("What is the approximate human genome size (base pairs)?", ["~300 million", "~3 billion", "~30 billion", "~300 billion"], 1),
    ("What is the term for symbiosis where both benefit?", ["Parasitism", "Mutualism", "Commensalism", "Amensalism"], 1),
    ("What is the Planck length (order, meters)?", ["10⁻¹⁵", "10⁻³⁵", "10⁻⁵", "10⁻²"], 1),
    ("What is the name of the process that makes mRNA from DNA?", ["Translation", "Transcription", "Replication", "Reverse transcription"], 1),
    ("What is the approximate salinity of seawater (ppt)?", ["~3.5", "~35", "~350", "~0.35"], 1),
    ("What is the term for an atom with a full valence shell (noble gas)?", ["Radical", "Inert", "Ionized", "Excited"], 1),
    ("What is the approximate resting potential of a neuron (mV)?", ["+40", "-70", "0", "-120"], 1),
    ("What is the main output of the Calvin cycle?", ["ATP", "Glucose", "NADPH", "Oxygen"], 1),
    ("What is the term for the study of earthquakes?", ["Volcanology", "Seismology", "Geology", "Meteorology"], 1),
    ("What is the approximate mass of an electron relative to a proton?", ["Same", "~1/1,836", "~1/200", "~1/10"], 1),
    ("What is the name of the blood vessels that carry blood toward the heart?", ["Arteries", "Veins", "Capillaries", "Venules"], 1),
    ("What is the pH of gastric acid (approx.)?", ["1–2", "7", "10", "14"], 0),
    ("What is the term for a diploid cell producing haploid gametes?", ["Mitosis", "Meiosis", "Binary fission", "Budding"], 1),
    ("What is the approximate percentage of water in the human body?", ["~30%", "~60%", "~90%", "~40%"], 1),
    ("What is the name of the force carrier for electromagnetism?", ["Gluon", "Photon", "W boson", "Graviton"], 1),
    ("What is the approximate wavelength of red visible light (nm)?", ["~400", "~700", "~200", "~900"], 1),
    ("What is the term for organisms that live without oxygen?", ["Aerobic", "Anaerobic", "Autotrophic", "Photosynthetic"], 1),
    ("What is the largest bone in the human skull?", ["Mandible", "Maxilla", "Frontal", "Parietal"], 0),
    ("What is the approximate number of human genes (protein-coding, order)?", ["~3,000", "~20,000", "~100,000", "~1 million"], 1),
    ("What is the name of the layer of Earth between crust and mantle?", ["Outer core", "Mantle", "Lithosphere", "Asthenosphere"], 2),
    ("What is the term for a substance that speeds a reaction without being consumed?", ["Substrate", "Catalyst", "Inhibitor", "Cofactor"], 1),
    ("What is the approximate first ionization energy of helium (eV)?", ["13.6", "24.6", "54.4", "79.0"], 1),
    ("What is the main nitrogenous waste in humans?", ["Uric acid", "Urea", "Ammonia", "Creatine"], 1),
    ("What is the term for the study of fungi?", ["Botany", "Mycology", "Virology", "Bacteriology"], 1),
    ("What is the approximate mass of the Sun compared to Earth?", ["~100,000×", "~330,000×", "~1 million×", "~1 billion×"], 1),
    ("What is the name of the blood protein that carries oxygen?", ["Albumin", "Hemoglobin", "Fibrinogen", "Insulin"], 1),
    ("What is the approximate pH of blood?", ["6.0", "7.4", "8.5", "5.5"], 1),
    ("What is the term for a graph of decay of a radioactive sample?", ["Phase diagram", "Decay curve", "Titration curve", "Calibration curve"], 1),
    ("What is the approximate number of chromosomes in humans (diploid)?", ["23", "46", "48", "44"], 1),
    ("What is the name of the process by which plants orient toward light?", ["Gravitropism", "Phototropism", "Hydrotropism", "Thigmotropism"], 1),
    ("What is the approximate altitude of the International Space Station (km)?", ["~120", "~400", "~1,000", "~36,000"], 1),
    ("What is the term for the fluid inside cells?", ["Plasma", "Cytoplasm", "Interstitial fluid", "Lymph"], 1),
    ("What is the approximate bond length of H–H (Å)?", ["0.37", "0.74", "1.10", "1.54"], 1),
    ("What is the industrial process that synthesizes ammonia from nitrogen and hydrogen?", ["Haber-Bosch", "Solvay process", "Contact process", "Hall–Héroult"], 0),
]

TG_RUIN: list[tuple[str, list[str], int]] = [
    ("What is Planck's constant (J·s, approximate)?", ["1.6×10⁻¹⁹", "6.626×10⁻³⁴", "9.1×10⁻³¹", "3×10⁸"], 1),
    ("What is the approximate Landé g-factor for a free electron?", ["~1", "~2.002", "~3", "~0.5"], 1),
    ("What percentage of the human genome codes for proteins (roughly)?", ["~50%", "~25%", "~1.5%", "~10%"], 2),
    ("How many known moons does Saturn have (as of 2024, commonly cited)?", ["82", "96", "124", "146"], 3),
    ("What is the approximate proton-to-electron mass ratio?", ["~511", "~1,836", "~2,400", "~10,000"], 1),
    ("What is the escape velocity of Earth (km/s)?", ["7.9", "11.2", "15.4", "25"], 1),
    ("What is Avogadro's number (per mole)?", ["6.02×10²³", "3.14×10⁸", "9.81", "1.38×10⁻²³"], 0),
    ("What is the approximate age of the oldest known Earth zircon (billions of years)?", ["~2.5", "~4.4", "~6.0", "~1.0"], 1),
    ("What is the approximate number of neurons in the human brain (order)?", ["~1 billion", "~86 billion", "~1 trillion", "~10 billion"], 1),
    ("What is the approximate energy of a photon of green light (eV)?", ["~0.1", "~2.3", "~10", "~100"], 1),
    ("What is the half-life of Carbon-14 (years)?", ["~1,000", "~5,730", "~50,000", "~100"], 1),
    ("What is the approximate salinity of human blood (g/L)?", ["~0.9", "~9", "~90", "~900"], 1),
    ("What is the name of the deepest ocean trench?", ["Puerto Rico", "Mariana", "Java", "Tonga"], 1),
    ("What is the approximate number of species described on Earth (order)?", ["~200,000", "~2 million", "~20 million", "~200 million"], 1),
    ("What is the Schwarzschild radius proportional to?", ["Mass", "Mass squared", "Charge", "Temperature"], 0),
    ("What is the approximate pKa of the side chain of histidine (imidazole)?", ["~4", "~6", "~10", "~12"], 1),
    ("What is the approximate wavelength of a 100 MHz radio wave in vacuum (m)?", ["0.3", "3", "30", "300"], 1),
    ("What is the term for RNA that catalyzes reactions?", ["mRNA", "tRNA", "Ribozyme", "siRNA"], 2),
    ("What is the approximate number of heartbeats in an average human lifetime?", ["~1 billion", "~2.5 billion", "~3 billion", "~5 billion"], 2),
    ("What is the approximate depth of Challenger Deep (miles)?", ["~3.5", "~7", "~12", "~1"], 1),
]
